# Maintainer: Mickael "PAPAMICA" Asseline
# Update: 2022-05-28

#& type: 3
#& title: Autoheal
#& description: Restart your container when unhealthy
#& note: Website: <a href='https://github.com/willfarrell/docker-autoheal' target='_blank' rel='noopener'>Github.com</a>
#& categories: SelfHosted, Docker, PAPAMICA
#& platform: linux
#& logo: https://img.papamica.com/logo/autoheal.png

#% SERVICE: Name of the service (No spaces or points) [autoheal]
#% NETWORK: Your Traefik network (Example: proxy) [proxy]


# Work with Portainer
services:
  autoheal:
    image: willfarrell/autoheal
    container_name: $SERVICE
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    networks:
      - default
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
networks:
  default:
    external:
      name: $NETWORK