# Maintainer: Mickael "PAPAMICA" Asseline
# Update: 2022-05-10

#& type: 3
#& title: Filebot
#& description: The ultimate TV and Movie Renamer
#& note: Website: <a href='https://www.filebot.net/' target='_blank' rel='noopener'>filebot.net</a>
#& categories: SelfHosted, PAPAMICA
#& platform: linux
#& logo: https://img.papamica.com/logo/filebot.svg

#% SERVICE: Name of the service (No spaces or points) [filebot]
#% DATA_LOCATION: Data localization (Example: /apps/service) [/_data/apps]
#% FOLDER: Folder of yours files (Example: /data/movies)
#% URL: Service URL (Example: service.papamica.fr or service.com)
#% NETWORK: Your Traefik network (Example: proxy) [proxy]

# Work with Portainer
version: "2"

services:
  # Filebot : https://www.filebot.net/
  filebot:
    image: jlesage/filebot:latest
    container_name: $SERVICE
    volumes:
      - $DATA_LOCATION/$SERVICE/config:/config:rw
      - $FOLDER:/storage:rw
    restart: always
    healthcheck:
      test: curl --fail http://localhost:5800 || exit 1
      interval: 1m
      timeout: 30s
      retries: 3
    networks:
      - default
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=5800"
      - "traefik.docker.network=$NETWORK"

networks:
  default:
    external:
      name: $NETWORK