# Maintainer: Mickael "PAPAMICA" Asseline
# Update: 2022-05-30

#& type: 3
#& title: Minecraft Java server
#& description: Minecraft server for Java edition.
#& note: Website: <a href='https://github.com/itzg/docker-minecraft-server' target='_blank' rel='noopener'>Github.com</a>
#& categories: SelfHosted, Game, PAPAMICA
#& platform: linux
#& logo: https://img.papamica.com/logo/minecraft.png

#% SERVICE: Name of the service (No spaces or points) [minecraft-server]
#% DATA_LOCATION: Data localization (Example: /apps/service) [/_data/apps]
#% URL: Service URL (Example: service.papamica.fr or service.com)
#% NETWORK: Your Traefik network (Example: proxy) [proxy]
#% TYPE: Type of server (VANILLA/FORGE/FABRIC/QUILT/SPIGOT/etc...) [VANILLA]
#% VERSION: Version of server (LATEST/SNAPSHOT/1.7.8/x.x.x) [LATEST]
#% PORT: Port of server (Default: 25565) [25565]
#% MOTD: MOTD (Description) [Minecraft server powered by §l§cPAPAMICA§r]
#% MODE: Game mode (creative/survival/adventure/spectator) [survival]
#% DIFFICULTY: Difficulty (peaceful/easy/normal/hard) [normal]
#% OPS: Admin users (OP) [PAPAMICA]
#% MAX_PLAYERS: Max players (Number) [20]
#% ALLOW_NETHER: Allow Nether (True/False) [True]
#% ENABLE_COMMAND_BLOCK: Enable command blok (True/False) [True]
#% HARDCORE: Enable hardcore (True/False) [False]
#% PVP: Enable PVP (True/False) [True]
#% ONLINE_MODE: Enable Online mode (True/False) [True]
#% ENABLE_AUTOPAUSE: Enable autopause (True/False) [True]


# Work with Portainer
version: "2"
services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: $SERVICE
    restart: always
    volumes:
      - $DATA_LOCATION/$SERVICE/data:/data
    environment:
      - "TYPE=$TYPE"
      - "VERSION=$VERSION"
      - "EULA=TRUE"
      - "OVERRIDE_SERVER_PROPERTIES=true"
      - MOTD="$MOTD"
      - DIFFICULTY=$DIFFICULTY
      - OPS=$OPS
      - MAX_PLAYERS=$MAX_PLAYERS
      - ALLOW_NETHER=$ALLOW_NETHER
      - ENABLE_COMMAND_BLOCK=$ENABLE_COMMAND_BLOCK
      - HARDCORE=$HARDCORE
      - MODE=$MODE
      - PVP=$PVP
      - ONLINE_MODE=$ONLINE_MODE
      - PORT=$PORT
      - ENABLE_AUTOPAUSE=$ENABLE_AUTOPAUSE
    networks:
      - default
    ports:
      - $PORT:$PORT
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater

networks:
  default:
    external:
      name: $NETWORK