# Maintainer: Mickael "PAPAMICA" Asseline
# Update: 2022-05-12

#& type: 3
#& title: Mumble Bot
#& description: Bot for Mumble server
#& note: Website: <a href='https://github.com/matthieugrieger/mumbledj' target='_blank' rel='noopener'>Github.com</a></br>You need to create a conf file "mumbledj.yaml"
#& categories: SelfHosted, PAPAMICA
#& platform: linux
#& logo: https://img.papamica.com/logo/mumblebot.png

#% SERVICE: Name of the service (No spaces or points) [mumble-bot]
#% DATA_LOCATION: Data localization (Example: /apps/service) [/_data/apps]
#% NETWORK: Your Traefik network (Example: proxy)

# Work with Portainer
version: "2"
services:
  mumble-bot:
    image: mattikus/mumbledj
    restart: always
    container_name: $SERVICE
    volumes:
      - $DATA_LOCATION/$SERVICE/mumbledj.yaml:/etc/mumbledj.yaml
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
    networks:
      - default

networks:
  default:
    external:
      name: $NETWORK