# Maintainer: Mickael "PAPAMICA" Asseline
# Update: 2022-05-17

#& type: 3
#& title: Nzbget
#& description: Nzbget is a usenet downloader, written in C++ and designed with performance in mind to achieve maximum download speed by using very little system resources.
#& note: Website: <a href='http://nzbget.net/' target='_blank' rel='noopener'>Nzbget.net</a>
#& categories: SelfHosted, Mediacenter, PAPAMICA
#& platform: linux
#& logo: https://img.papamica.com/logo/nzbget.png

#% SERVICE: Name of the service (No spaces or points) [nzbget]
#% DATA_LOCATION: Data localization (Example: /apps/service) [/_data/apps]
#% URL: Service URL (Example: service.papamica.fr or service.com)
#% NETWORK: Your Traefik network (Example: proxy) [proxy]
#% TZ: Time zone (Exemple: Europe/Paris) [Europe/Paris]
#% NZBGET_USER: User for application (Exemple: PAPAMICA) [PAPAMICA]
#% NZBGET_PASS: Password for application
#% FOLDER_DOWNLOAD: Your download folder (Exemple: /data/download)


# Work with Portainer
services:
  nzbget:
    image: linuxserver/nzbget:latest
    container_name: $SERVICE
    restart: always
    volumes:
      - $DATA_LOCATION/$SERVICE/config:/config
      - $FOLDER_DOWNLOAD:/downloads
    environment:
      - NZBGET_USER=$NZBGET_USER
      - NZBGET_PASS=$NZBGET_PASS
      - TZ=$TZ
      - PUID=1000
      - PGID=1000
    healthcheck:
      test: curl --connect-timeout 15 --max-time 100 --silent --show-error --fail "http://localhost:6789" > /dev/null
      interval: 1m
      timeout: 30s
      retries: 3
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=6789"
      - "traefik.docker.network=$NETWORK"
    networks:
      - default
networks:
  default:
    external:
      name: $NETWORK