# Maintainer: Mickael "PAPAMICA" Asseline
# Update: 2022-05-12

#& type: 3
#& title: Sinusbot
#& description: Bot for TeamSpeak and Discord
#& note: Website: <a href='https://www.sinusbot.com/' target='_blank' rel='noopener'>Sinusbot.com</a>
#& categories: SelfHosted, PAPAMICA
#& platform: linux
#& logo: https://img.papamica.com/logo/sinusbot.png

#% SERVICE: Name of the service (No spaces or points) [sinusbot]
#% DATA_LOCATION: Data localization (Example: /apps/service) [/_data/apps]
#% URL: Service URL (Example: service.papamica.fr or service.com)
#% NETWORK: Your Traefik network (Example: proxy) [proxy]

# Work with Portainer
version: "2"
services:
  sinusbot:
    image: sinusbot/docker:latest
    container_name: $SERVICE
    restart: always
    volumes:
      - $DATA_LOCATION/$SERVICE/scripts:/opt/sinusbot/scripts
      - $DATA_LOCATION/$SERVICE/data:/opt/sinusbot/data
    networks:
      - default
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=8087"
      - "traefik.docker.network=$NETWORK"

networks:
  default:
    external:
      name: $NETWORK