# Maintainer: Mickael "PAPAMICA" Asseline
# Update: 2022-05-10

#& type: 3
#& title: Vaultwarden
#& description: Password manager
#& note: Website: <a href='https://github.com/dani-garcia/vaultwarden' target='_blank' rel='noopener'>Github.com</a>
#& categories: SelfHosted, PAPAMICA
#& platform: linux
#& logo: https://img.papamica.com/logo/bitwarden.png

#% SERVICE: Name of the service (No spaces or points) [vaultwarden]
#% DATA_LOCATION: Data localization (Example: /apps/service) [/_data/apps]
#% URL: Service link (Example: service.papamica.fr or service.com)
#% NETWORK: Your Traefik network (Example: proxy) [proxy]
#% SIGNUPS_ALLOWED: Autorize signup ? (True or False) [True]
#% TIME_ZONE: Time zone (Example : Europe/Paris) [Europe/Paris]
#% ADMIN_TOKEN: Admin token (For manage with url/admin)

# Work with Portainer
version: "2"
services:
  # Bitwarden : https://bitwarden.com/
  bitwarden:
    image: vaultwarden/server:latest
    container_name: $SERVICE
    restart: always
    volumes:
      - $DATA_LOCATION/$SERVICE/bw-data:/data
    environment:
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
      SIGNUPS_ALLOWED: '$SIGNUPS_ALLOWED'   # set to false to disable signups
      TZ: '$TIME_ZONE'
      ADMIN_TOKEN: '$ADMIN_TOKEN'
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 1m
      timeout: 30s
      retries: 3
    ports:
      - 3012:3012
    networks:
      - default
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.docker.network=$NETWORK"
networks:
  default:
    external:
      name: $NETWORK