# Maintainer: Mickael "PAPAMICA" Asseline
# Update: 2022-05-11

#& type: 3
#& title: WordPress
#& description: WordPress is open source software you can use to create a beautiful website, blog, or app.
#& note: Website: <a href='https://wordpress.org/' target='_blank' rel='noopener'>WordPress.org</a>
#& categories: SelfHosted, PAPAMICA
#& platform: linux
#& logo: https://img.papamica.com/logo/wordpress.png

#% SERVICE: Name of the service (No spaces or points) [wordpress]
#% DATA_LOCATION: Data localization (Example: /apps/service) [/_data/apps]
#% URL: Service link (Example: service.papamica.fr or service.com)
#% NETWORK: Your Traefik network (Example: proxy) [proxy]
#% DB_USER: Database user (No spaces or points) [wordpress]
#% DB_PASSWORD: Password for database user
#% DB_ROOT: Password for database root

# Work with Portainer
version: "2"

services:
  # Base de données
  wordpress-db:
    container_name: $SERVICE-db
    image: mysql:5.7
    volumes:
      - $DATA_LOCATION/$SERVICE/db:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT
      MYSQL_DATABASE: wordpress
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    networks:
      - default
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater

  wordpress:
    container_name: $SERVICE
    depends_on:
      - wordpress-db
    image: wordpress:latest
    restart: always
    volumes:
      - $DATA_LOCATION/$SERVICE/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - $DATA_LOCATION/$SERVICE/html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: $SERVICE-db:3306
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_DB_NAME: wordpress
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 1m
      timeout: 30s
      retries: 3
    networks:
      - default
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.docker.network=$NETWORK"

networks:
  default:
    external:
      name: $NETWORK