colors:
    primary:
      background: '0x2b3841'
      foreground: '0x757ea1'

  # Normal colors
    normal:
      black:   '0x08090d'
      red:     '0x6c2630'
      green:   '0x249f8b'
      yellow:  '0xd3894c'
      blue:    '0x006ec7'
      magenta: '0x9e78e9'
      cyan:    '0x60b6d1'
      white:   '0x454350'

  # Bright colors
    bright:
      black:   '0x8b8a8a'
      red:     '0xd04a5d'
      green:   '0x8dd194'
      yellow:  '0xdab531'
      blue:    '0x02c3ee'
      magenta: '0xb294bb'
      cyan:    '0x60b6d1'
      white:   '0xcdc5b8'


