colors:
  primary:
    background: '0x060606'
    foreground: '0xafafaf'

  # Normal colors
  normal:
    black:   '0x575757'
    red:     '0x9d0102'
    green:   '0x797979'
    yellow:  '0x919191'
    blue:    '0x4b5054'
    magenta: '0x5e5e5e'
    cyan:    '0x515151'
    white:   '0x585858'

  # Bright colors
  bright:
    black:   '0x1f1f1f'
    red:     '0x9d0102'
    green:   '0xa2a2a2'
    yellow:  '0x868686'
    blue:    '0x9b9ea1'
    magenta: '0x909090'
    cyan:    '0x747572'
    white:   '0xafafaf'


