colors:
# Default colors
  primary:
    background: '#080808'
    foreground: '#b2b2b2'

    # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '#080808'
    cursor: '#b2b2b2'

    # Normal colors
  normal:
    black:   '#323437'
    red:     '#ff5454'
    green:   '#8cc85f'
    yellow:  '#e3c78a'
    blue:    '#80a0ff'
    magenta: '#d183e8'
    cyan:    '#79dac8'
    white:   '#c6c6c6'

    # Bright colors
  bright:
    black:   '#949494'
    red:     '#ff5189'
    green:   '#36c692'
    yellow:  '#bfbf97'
    blue:    '#74b2ff'
    magenta: '#ae81ff'
    cyan:    '#85dc85'
    white:   '#e4e4e4'
