colors:
  primary:
    background: '0x0f111a'
    foreground: '0xD8DEE9'
  cursor:
    cursor: '0xff4151'
  normal:
    black:      '0x4C566A'
    red:        '0xBF616A'
    green:      '0xA3BE8C'
    yellow:     '0xEBCB8B'
    blue:       '0x81A1C1'
    magenta:    '0xB48EAD'
    cyan:       '0x88C0D0'
    white:      '0xE5E9F0'


