colors:
  primary:
    background: '0x2e5d55'
    foreground: '0xffe7ab'

  # Normal colors
  normal:
    black:   '0x282a2e'
    red:     '0xaf3122'
    green:   '0x509e90'
    yellow:  '0xfe9b72'
    blue:    '0x248f89'
    magenta: '0x85678f'
    cyan:    '0x5e8d87'
    white:   '0x707880'

  # Bright colors
  bright:
    black:   '0x373b41'
    red:     '0xcc6666'
    green:   '0x228c8a'
    yellow:  '0xffb860'
    blue:    '0x1d8681'
    magenta: '0xb294bb'
    cyan:    '0x8abeb7'
    white:   '0xdbc2a4'


