colors:
  # Default colors
  primary:
    background: '0x110700'
    foreground: '0xbb5600'

  # Normal colors
  normal:
    black:   '0x110800'
    red:     '0x773b00'
    green:   '0xbb6000'
    yellow:  '0x774000'
    blue:    '0x994900'
    magenta: '0xbb6000'
    cyan:    '0x552200'
    white:   '0xbb6400'

  # Bright colors
  bright:
    black:   '0x773200'
    red:     '0x774200'
    green:   '0xbb6400'
    yellow:  '0x774400'
    blue:    '0x995200'
    magenta: '0xbb7200'
    cyan:    '0x552400'
    white:   '0xff8800'

