colors:
  # Default colors
  primary:
    background: '0xffffff'
    foreground: '0x9925ba'

  # Normal colors
  normal:
    black:   '0x2b2b2b'
    red:     '0xbc545e'
    green:   '0xa5c261'
    yellow:  '0xc9861c'
    blue:    '0x464c95'
    magenta: '0xa5a3d5'
    cyan:    '0x519f50'
    white:   '0x8e7796'

  # Bright colors
  bright:
    black:   '0x774fba'
    red:     '0xd24a3b'
    green:   '0xa5c261'
    yellow:  '0xe99716'
    blue:    '0x8065cd'
    magenta: '0x78769e'
    cyan:    '0x519f50'
    white:   '0x2a2a2a'

