#podman / docker build -t <name> .
FROM registry.fedoraproject.org/fedora:37 

RUN echo -e "[main]\ngpgcheck=1\ninstallonly_limit=3\nfastestmirror=true\nmax_parallel_downloads=15\n" | tee /etc/dnf/dnf.conf



RUN dnf install  --setopt=tsflags=nodocs --setopt=install_weak_deps=False cargo tree-sitter-cli htop hyperfine just bat fzf gh just make neofetch neovim npm python3 python3-pip jq git curl gcc-c++ gcc wget -y


#LINKING DOCKER PODMAN AND FLATPAK
RUN   ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/flatpak && \ 
      ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/podman

COPY set_config.sh /usr/local/bin/set_config
RUN chmod +x /usr/local/bin/set_config


COPY .config /usr/local/config/
#RUN git clone https://github.com/siduck76/NvChad /usr/local/config/.config/nvim --depth 1
RUN git clone --depth 1 https://github.com/AstroNvim/AstroNvim /usr/local/config/.config/nvim --depth 1
#https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/NerdFontsSymbolsOnly.zip
#mkdir ~/.local/share/fonts
#unzip NerdFontsSymbolsOnly.zip -d ~/.local/share/fonts/
#fc-cache ~/.local/share/fonts
RUN python3 -m pip install beautifulsoup4 requests fastapi scrapy numpy
