#!/bin/bash

# Retrieve monitor names using xrandr and cut command
monitor_names=$(xrandr --listmonitors | tail -n +2 | cut -d' ' -f6-)

echo " monitors : $monitor_names"
# Set monitor names as environment variables
export PRIMARY_MONITOR_NAME=$(echo "$monitor_names" | head -n 1)
if [ "$(echo "$monitor_names" | wc -l)" -gt 1 ]; then
  export SECONDARY_MONITOR_NAME=$(echo "$monitor_names" | tail -n 1)

  # Check if the second monitor is already active
  if ! xrandr --listactivemonitors | grep -q "$SECONDARY_MONITOR_NAME"; then
    # Activate the second monitor and set the desired resolution
    xrandr --output "$SECONDARY_MONITOR_NAME" --auto --preferred
  fi
else
  export SECONDARY_MONITOR_NAME=$PRIMARY_MONITOR_NAME
fi

