#podman / docker build -t <name> .

FROM registry.fedoraproject.org/fedora:37 

COPY extra-packages /
RUN dnf update && \
    dnf upgrade && \
    grep -v '^#' /extra-packages | xargs dnf install
RUN rm /extra-packages


#LINKING DOCKER PODMAN AND FLATPAK
RUN   ln -fs /bin/sh /usr/bin/sh && \
      ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/docker && \
      ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/flatpak && \ 
      ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/podman && \
      ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/rpm-ostree && \
      ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/transactional-update

COPY set_config.sh /usr/local/bin/set_config
RUN chmod +x set_config
COPY starship.toml /usr/local/starship.toml

RUN chmod +x /usr/local/bin/set_config

RUN python3 -m pip install beautifulsoup4 requests fastapi scrapy numpy
