FROM quay.io/toolbx-images/alpine-toolbox:edge

LABEL com.github.containers.toolbox="true" \
      usage="This image is meant to be used with the toolbox or distrobox command" \
      summary="A cloud-native terminal experience" \
      maintainer="jorge.castro@gmail.com>"

COPY extra-packages /
RUN apk update && \
    apk upgrade && \
    grep -v '^#' /extra-packages | xargs apk add
RUN rm /extra-packages

#NVCHAD
RUN   rm -rf ~/.config/nvim &&\
      rm -rf ~/.local/share/nvim &&\
      rm -rf ~/.cache/nvim &&\
      mkdir .config &&\
      git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1

#LINKING DOCKER PODMAN AND FLATPAK
RUN   ln -fs /bin/sh /usr/bin/sh && \
      ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/docker && \
      ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/flatpak && \ 
      ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/podman && \
      ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/rpm-ostree && \
      ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/transactional-update
   
#OMT   
RUN   cd &&\
      git clone https://github.com/mehdi-yc/.tmux.git &&\
      ln -s -f .tmux/.tmux.conf &&\
      cp .tmux/.tmux.conf.local . 
  
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

RUN cd && touch .bashrc && source .bashrc && echo 'eval "$(starship init bash)"' >> ~/.bashrc

RUN python3 -m pip install beautifulsoup4 requests fastapi scrapy 
