FROM quay.io/toolbx-images/alpine-toolbox:edge

COPY extra-packages /
RUN apk update && \
    apk upgrade && \
    grep -v '^#' /extra-packages | xargs apk add
RUN rm /extra-packages

#NVCHAD
RUN   rm -rf ~/.config/nvim &&\
      rm -rf ~/.local/share/nvim &&\
      rm -rf ~/.cache/nvim &&\
      mkdir .config &&\
      git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1

#LINKING DOCKER PODMAN AND FLATPAK
RUN   ln -fs /bin/sh /usr/bin/sh && \
      ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/docker && \
      ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/flatpak && \ 
      ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/podman && \
      ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/rpm-ostree && \
      ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/transactional-update
   
#OMT   
RUN   cd &&\
      git clone https://github.com/mehdi-yc/.tmux.git &&\
      ln -s -f .tmux/.tmux.conf &&\
      cp .tmux/.tmux.conf.local . 
  
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
ENV PATH="~/.cargo/bin:${PATH}"

RUN cd && touch .bashrc && source .bashrc && echo 'eval "$(starship init bash)"' >> ~/.bashrc
RUN touch .bash_profile
RUN cat << EOF >> # ~/.bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
. "$HOME/.cargo/env"
EOF



RUN python3 -m pip install beautifulsoup4 requests fastapi scrapy 
