# Maintainer: Mickael "PAPAMICA" Asseline
# Update: 2022-05-10

#& type: 3
#& title: Jirafeau
#& description: Jirafeau is a "one-click-filesharing": Select your file, upload, share a link. That's it.
#& note: Website: <a href='https://gitlab.com/mojo42/Jirafeau' target='_blank' rel='noopener'>Gitlab.com</a>
#& categories: SelfHosted, PAPAMICA
#& platform: linux
#& logo: https://img.papamica.com/logo/jirafeau.png

#% SERVICE: Name of the service (No spaces or points) [jirafeau]
#% DATA_LOCATION: Data localization (Example: /apps/service) [/_data/apps]
#% URL: Service URL (Example: service.papamica.fr or service.com)
#% NETWORK: Your Traefik network (Example: proxy) [proxy]

# Work with Portainer
version: '2'

services:
  jirafeau:
    image: jgeusebroek/jirafeau
    container_name: $SERVICE
    restart: unless-stopped
    volumes:
      - $DATA_LOCATION/$SERVICE/cfg:/cfg
      - $DATA_LOCATION/$SERVICE/data:/data
      #- $DATA_LOCATION/$SERVICE/media:/jirafeau/media
    healthcheck:
      test: wget -nv -t1 --spider 'http://localhost:80'
      interval: 1m
      timeout: 30s
      retries: 3
    networks:
      - default
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.docker.network=$NETWORK"

networks:
  default:
    external:
      name: $NETWORK