# Maintainer: Mickael "PAPAMICA" Asseline
# Update: 2022-05-17

#& type: 3
#& title: Lidarr
#& description: Lidarr is a music collection manager for Usenet and BitTorrent users.
#& note: Website: <a href='https://lidarr.audio/' target='_blank' rel='noopener'>Lidarr.audio</a>
#& categories: SelfHosted, Mediacenter, PAPAMICA
#& platform: linux
#& logo: https://img.papamica.com/logo/lidarr.png

#% SERVICE: Name of the service (No spaces or points) [lidarr]
#% DATA_LOCATION: Data localization (Example: /apps/service) [/_data/apps]
#% URL: Service URL (Example: service.papamica.fr or service.com)
#% NETWORK: Your Traefik network (Example: proxy) [proxy]
#% TZ: Time zone (Exemple: Europe/Paris) [Europe/Paris]
#% FOLDER_DOWNLOAD: Your download folder (Exemple: /data/download)
#% FOLDER_MUSIC: Your musics folder (Exemple: /data/musics)


# Work with Portainer
services:
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: $SERVICE
    restart: always
    volumes:
      - $DATA_LOCATION/$SERVICE/config:/config
      - $FOLDER_DOWNLOAD/sonarr:/downloads
      - $FOLDER_MOVIES:/music
    environment:
      - TZ=$TZ
      - PUID=1000
      - PGID=1000
    healthcheck:
      test: curl --connect-timeout 15 --max-time 100 --silent --show-error --fail "http://localhost:8686" > /dev/null
      interval: 1m
      timeout: 30s
      retries: 3
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=8686"
      - "traefik.docker.network=$NETWORK"
    networks:
      - default
networks:
  default:
    external:
      name: $NETWORK