version: "3.8"
services:
  lightdash:
    image: lightdash/lightdash:latest
    depends_on:
      - db
    environment:
      - PGHOSTdb
      - PGPORT5432
      - PGUSERpostgres
      - PGPASSWORD=PGPASSWORD
      - PGDATABASEpostgres
      - SECURE_COOKIESfalse
      - TRUST_PROXYfalse
      - LIGHTDASH_SECRET=LIGHTDASH_SECRET
      - PORT8080
      - LIGHTDASH_LOG_LEVEL=LIGHTDASH_LOG_LEVEL
      - LIGHTDASH_INSTALL_ID=LIGHTDASH_INSTALL_ID
      - LIGHTDASH_INSTALL_TYPEdocker_image
      - AUTH_DISABLE_PASSWORD_AUTHENTICATION=AUTH_DISABLE_PASSWORD_AUTHENTICATION
      - AUTH_GOOGLE_OAUTH2_CLIENT_ID=AUTH_GOOGLE_OAUTH2_CLIENT_ID
      - AUTH_GOOGLE_OAUTH2_CLIENT_SECRET=AUTH_GOOGLE_OAUTH2_CLIENT_SECRET
      - SITE_URL=SITE_URL
      - EMAIL_SMTP_HOST=EMAIL_SMTP_HOST
      - EMAIL_SMTP_PORT=EMAIL_SMTP_PORT
      - EMAIL_SMTP_SECURE=EMAIL_SMTP_SECURE
      - EMAIL_SMTP_USER=EMAIL_SMTP_USER
      - EMAIL_SMTP_PASSWORD=EMAIL_SMTP_PASSWORD
      - EMAIL_SMTP_ALLOW_INVALID_CERT=EMAIL_SMTP_ALLOW_INVALID_CERT
      - EMAIL_SMTP_SENDER_NAME=EMAIL_SMTP_SENDER_NAME
      - EMAIL_SMTP_SENDER_EMAIL=EMAIL_SMTP_SENDER_EMAIL
      - ALLOW_MULTIPLE_ORGSfalse
      - LIGHTDASH_QUERY_MAX_LIMIT=LIGHTDASH_QUERY_MAX_LIMIT
      - LIGHTDASH_MAX_PAYLOAD5mb
      - HEADLESS_BROWSER_HOST=headless-browser
      - HEADLESS_BROWSER_PORT=3000
      - RUDDERSTACK_WRITE_KEY=RUDDERSTACK_WRITE_KEY
    volumes:
      - "DBT_PROJECT_DIR:/usr/app/dbt"
    ports:
      - PORT:-8080:PORT:-8080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: PGPASSWORD
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  headless-browser:
    image: browserless/chrome
    restart: always
    ports:
      - "3001:3000"

  scheduler:
    image: lightdash/lightdash:latest
    entrypoint: ["yarn", "workspace", "backend", "scheduler"]
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=PGPASSWORD
      - PGDATABASE=postgres
      - LIGHTDASH_SECRET=LIGHTDASH_SECRET


volumes:
  db-data:
