# Maintainer: Mickael "PAPAMICA" Asseline
# Update: 2022-05-12

#& type: 3
#& title: TeamSpeak
#& description: Vocal server perfect for teamplay
#& note: Website: <a href='https://teamspeak.com/en/' target='_blank' rel='noopener'>TeamSpeak.com</a></br>Ports to open: 9987, 10011, 30033 & 10022
#& categories: SelfHosted, PAPAMICA
#& platform: linux
#& logo: https://img.papamica.com/logo/teamspeak.png

#% SERVICE: Name of the service (No spaces or points) [teamspeak]
#% DATA_LOCATION: Data localization (Example: /apps/service) [/_data/apps]
#% URL: Service URL (Example: service.papamica.fr or service.com)
#% NETWORK: Your Traefik network (Example: proxy) [proxy]
#% ADMIN_PASS: Admin password

# Work with Portainer
version: '2'
services:
  teamspeak:
    image: mbentley/teamspeak
    restart: always
    container_name: $SERVICE
    volumes:
      - $DATA_LOCATION/$SERVICE/data:/data
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
      - 10022:10022
    environment:
      - UID=1000
      - GID=1000
      - TS3SERVER_LICENSE=accept
    command: serveradmin_password=$ADMIN_PASS
    labels:
      - autoupdate=monitor # https://github.com/PAPAMICA/container-updater
      - traefik.enable=true
      - traefik.http.routers.$SERVICE.rule=Host(`$URL`)
      - traefik.http.routers.$SERVICE.entryPoints=http
      - traefik.$SERVICE.port=9987
      - traefik.$SERVICE2.port=30033
      - traefik.SERVICE-query.port=10011
      - traefik.SERVICE-query2.port=10022
      - traefik.docker.network=$NETWORK
    networks:
      default:
        aliases:
          - $SERVICE.docker.local

networks:
  default:
    external:
      name: $NETWORK