matches:
  # Simple text replacements
  - trigger: ":ca"
    replace: "#YAHIA CHERIF Mohamed Mahdi add {{today}} : $|$ \n#Notion: \n#End YAHIA CHERIF Mohamed Mahdi {{today}}"
    vars:
      - name: today
        type: date
        params: 
          format: "%d/%m/%Y"
        
  - trigger: ":ce"
    replace: "#YAHIA CHERIF Mohamed Mahdi Edit {{today}} : $|$ \n#End YAHIA CHERIF Mohamed Mahdi {{today}}"
    vars:
      - name: today
        type: date
        params: 
          format: "%d/%m/%Y"

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # JSON Snippet
  - trigger: ":ss"
    replace: |
      {
      "One__":"badge badge-light-info rounded-pill",
      "Two__":"badge badge-light-success rounded-pill"
      }

  # If condition snippet
  - trigger: ":ia"
    replace: |
        if record.get("{{form.field}}") and record.get("{{form.field}}").name == "{{form.value}}":return True
        return False
    vars:
      - name: "form"
        type: form
        params:
          layout: "Field: [[field]] \nValue: [[value]]"


