theme = "monokai_pro_machine"

[editor]
bufferline = "multiple"

[editor.cursor-shape]
insert= "bar"

[keys.normal]
C-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
esc = ["collapse_selection","keep_primary_selection"]
C-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

