- name: Install DNF packages
  hosts: localhost
  vars:
    config_directories:
     - ~/.config/
     - ~/.config/nvim
     - ~/.config/i3
     - ~/.config/i3status
 #    - ~/.config/
 #    - ~/.config/
  tasks:

     
    - name: Enable COPRs
      become: true
      command: 'dnf copr enable {{ item }} -y'
      with_items:
        - alciregi/distrobox
        - zeno/scrcpy
        - atim/starship
        - atim/nushell
        

    - name: Install packages
      become: true
      dnf:
        name:
          - cargo
          - rustc
          - tmux
          - htop
          - docker-compose
          - python3-pip
          - wget
          - curl
          - neovim
          - git
          - nodejs
          - npm
          - ansible
          - afetch
          - gcc
          - jq
          - unzip
          - zip
          - bat
          - hyperfine
          - tokei
          - just
          - nushell
          - starship
        state: present
        update_cache: false
        install_weak_deps: false
        disable_gpg_check: 'yes'
          
          
    - name: Install pip packages
      pip:
        name:
          - beautifulsoup4
          - numpy
          - pandas
          - matplotlib
          - requests
          - fastapi
          - scrapy
        state: present   
          
    - name: My Tmux config
      shell: |
            cd && git clone https://github.com/mehdi-yc/.tmux.git
            ln -s -f .tmux/.tmux.conf && cp .tmux/.tmux.conf.local .

    - name: creating config diractory
      file:
        path: "{{item}}"
        state: directory
      loop: "{{config_directories}}"
        
        
    - name: Download Config
      get_url:
        url: '{{ base_url }}{{ item.url }}'
        dest: '~/{{ item.dest }}'
        force: true
      loop:
        - url: i3/config
          dest: .config/i3/config
        - url: i3/gotonp.sh
          dest: .config/i3/gotonp.sh
        - url: i3status/config
          dest: .config/i3status/config
        - url: nvim.bk/init.lua
          dest: .config/nvim/init.lua
        - url: .bashrc
          dest: .bashrc
        - url: /starship.toml
          dest: .config/starship.toml
      vars:
        base_url: "https://raw.githubusercontent.com/Mehdi-YC/postinstall/main/distrobox_builder/.config/"
