- name: Install DNF packages
  hosts: localhost
  vars:
    config_path: "$HOME/repos/myconfig"

  tasks:

    - name: Enable COPRs
      become: true
      command: 'dnf copr enable {{ item }} -y'
      with_items:
#       - zeno/scrcpy
        - atim/starship
        - atim/nushell
      tags: minimal

      
    - name: Install minimal packages
      become: true
      dnf:
        name:
          - ranger
          - stow
          - fzf
          - tmux
          - htop
          - docker
          - docker-compose
          - python3-pip
          - neovim
          - git
          - bat
          - starship
        state: present
        update_cache: false
        install_weak_deps: false
        disable_gpg_check: 'yes'
      tags: minimal


    - name: Install packages
      become: true
      dnf:
        name:
          - stow
          - fzf
          - cargo
          - rustc
          - tmux
          - htop
          - docker
          - docker-compose
          - python3-pip
          - wget
          - curl
          - neovim
          - git
          - nodejs
          - npm
#          - ansible
          - afetch
          - jq
          - unzip
          - zip
          - bat
          - hyperfine
          - tokei
          - just
          - nushell
          - starship
        state: present
        update_cache: false
        install_weak_deps: false
        disable_gpg_check: 'yes'



    - name: Install pip packages
      pip:
        name:
          - beautifulsoup4
          - numpy
          - pandas
          - matplotlib
          - requests
          - fastapi
          - scrapy
          - django
        state: present   



    - name: Clone config
      git:
        repo: https://github.com/mehdi-yc/postinstall
        dest: "{{config_path}}"
        force: true
        update: true
      tags: minimal



    - name: Backup .bashrc and .Xresources
      command: mv "{{ item }}" "{{ item }}.bak"
      args:
        creates: "{{ item }}.bak"
      with_items:
        - ~/.bashrc
        - ~/.Xresources



    - name: Stow the config files
      command: stow -vRd "{{config_path}}/" -t $HOME config
      tags: minimal
    

    - name: chmod the i3 scripts
      command: chmod +x ~/.config/i3/gotonp.sh

    - name: ensure Fonts directory exists
      become: true
      file:
        path: /usr/share/fonts/truetype/
        recurse: true
        state: directory

    - name: Download FiraCode Regular Nerd Font
      become: true
      timeout: 300
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/raw/v3.0.2/patched-fonts/FiraCode/Regular/FiraCodeNerdFont-Regular.ttf
        dest: /usr/share/fonts/truetype/FiraCode-Regular.ttf