- name: Install DNF packages
  hosts: localhost
  vars:
    config_path: "$HOME/repos/myconfig"

  tasks:



        #DESKTOP
      
      
      - name: add vscodium repo with rpmkeys
        become: true
        shell: |
              rpmkeys --import https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
              printf "[gitlab.com_paulcarroty_vscodium_repo]\nname=download.vscodium.com\nbaseurl=https://download.vscodium.com/rpms/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg\nmetadata_expire=1h" | sudo tee -a /etc/yum.repos.d/vscodium.repo
        tags: desktop,fedora


      - name: add vscodium repo with debiankeys
        become: true
        shell: | 
                wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg \
                | gpg --dearmor \
                | sudo dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg
                &&  echo 'deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg ] https://download.vscodium.com/debs vscodium main' \
                | sudo tee /etc/apt/sources.list.d/vscodium.list
                && sudo apt update

 
          

      - name: Install Flatpak and vscode if necessary
        become: true
        package:
          name: 
            - flatpak
            - codium
          state: present



      - name: install i3 + config
        become: true
        package:
          name: 
            - i3
            - i3status
            - picom
            - dunst
          state: present




      - name: Install Flatpak Apps
        become: true
        flatpak:
          name:
            - rest.insomnia.Insomnia
            - org.pitivi.Pitivi
            - org.remmina.Remmina
            - org.gimp.GIMP
            - org.inkscape.Inkscape
            - com.discordapp.Discord
            - org.mozilla.firefox
            - com.valvesoftware.Steam
            - io.dbeaver.DBeaverCommunity
            - net.cozic.joplin_desktop
            - org.flameshot.Flameshot
          method: system
          state: present


      - name: Install vscodium extensions
        command: codium --install-extension "{{ item }}"
        with_items:
          - asvetliakov.vscode-neovim
          - bradlc.vscode-tailwindcss
          - innoverio.vscode-dbt-power-user
          - jdinhlife.gruvbox
          - ms-python.python
          - ms-toolsai.jupyter
          - ms-toolsai.jupyter-keymap
          - ms-toolsai.jupyter-renderers
          - ms-toolsai.vscode-jupyter-cell-tags
          - ms-toolsai.vscode-jupyter-slideshow
          - mtxr.sqltools
          - mtxr.sqltools-driver-pg
          - mtxr.sqltools-driver-sqlite
          - PKief.material-icon-theme
          - rust-lang.rust
          - rust-lang.rust-analyzer
          - s-nlf-fh.glassit
          - sainnhe.gruvbox-material
          - samuelcolvin.jinjahtml
          - svelte.svelte-vscode
          - tamasfe.even-better-toml
          - ultram4rine.sqltools-clickhouse-driver
          - vscodevim.vim
          - yandeu.five-server




      - name: Download Installer
        get_url:
          url: https://sh.rustup.rs
          dest: /tmp/sh.rustup.rs
          mode: '0755'
          force: 'yes'
        tags:
          - rust

      - name: install rust/cargo
        shell: /tmp/sh.rustup.rs -y