- name: Install DNF packages
  hosts: localhost
  vars:
    config_path: "$HOME/repos/myconfig"

  tasks:


    - name: Enable COPRs
      become: true
      command: 'dnf copr enable {{ item }} -y'
      with_items:
        - alciregi/distrobox
#       - zeno/scrcpy
        - atim/starship
        - atim/nushell
      tags: minimal

      
    - name: Install minimal packages
      become: true
      dnf:
        name:
          - ranger
          - stow
          - fzf
          - tmux
          - htop
          - python3-pip
          - neovim
          - git
          - bat
          #- hyperfine
          - tokei
          #- just
          - nushell
          - starship
          - fish
        state: present
        update_cache: false
        install_weak_deps: false
        disable_gpg_check: 'yes'
      tags: minimal


    - name: Install packages
      become: true
      dnf:
        name:
          - stow
          - fzf
          - cargo
          - rustc
          - tmux
          - htop
          - docker-compose
          - python3-pip
          - wget
          - curl
          - neovim
          - git
          - nodejs
          - npm
          - ansible
          - afetch
          - jq
          - unzip
          - zip
          - bat
          - hyperfine
          - tokei
          - just
          - nushell
          - starship
          - fish
        state: present
        update_cache: false
        install_weak_deps: false
        disable_gpg_check: 'yes'



    - name: Install pip packages
      pip:
        name:
          - beautifulsoup4
          - numpy
          - pandas
          - matplotlib
          - requests
          - fastapi
          - scrapy
        state: present   

    - name: Clone config
      git:
        repo: https://github.com/mehdi-yc/postinstall
        dest: "{{config_path}}"
        update: true

    - name: Stow the config files
      command: stow -vRd "{{config_path}}/distrobox_builder/" -t $HOME config

    - name: Add some fonts
      shell: |
              mkdir ~/.local/share/
              mkdir ~/.local/share/fonts 
              cd ~/.local/share/fonts 
              curl -fLo "Fira Code Regular Nerd Font Complete.ttf" https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/FiraCode/Regular/complete/Fira%20Code%20Regular%20Nerd%20Font%20Complete.ttf
      tags: minimal
