- name: Install DNF packages
  hosts: localhost
  vars:
    config_path: "$HOME/repos/myconfig"

  tasks:
    - name: Enable COPRs
      become: true
      command: 'dnf copr enable {{ item }} -y'
      with_items:
        - alciregi/distrobox
#        - zeno/scrcpy
        - atim/starship
        - atim/nushell

    - name: Install packages
      become: true
      dnf:
        name:
          - stow
          - fzf
          - cargo
          - rustc
          - tmux
          - htop
          - docker-compose
          - python3-pip
          - wget
          - curl
          - neovim
          - git
          - nodejs
          - npm
          - ansible
          - afetch
          - gcc
          - jq
          - unzip
          - zip
          - bat
          - hyperfine
          - tokei
          - just
          - nushell
          - starship
          - gcc-c++
        state: present
        update_cache: false
        install_weak_deps: false
        disable_gpg_check: 'yes'
          
    - name: Install pip packages
      pip:
        name:
          - beautifulsoup4
          - numpy
          - pandas
          - matplotlib
          - requests
          - fastapi
          - scrapy
        state: present   

    - name: Clone config
      git:
        repo: https://github.com/mehdi-yc/postinstall
        dest: "{{config_path}}"
        update: true

    - name: Stow the config files
      command: stow -vRd "{{config_path}}/distrobox_builder/" -t $HOME config

#https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/NerdFontsSymbolsOnly.zip
#mkdir ~/.local/share/fonts
#unzip NerdFontsSymbolsOnly.zip -d ~/.local/share/fonts/
#fc-cache ~/.local/share/fonts