- name: Desktop
  hosts: localhost
  become: true
  tasks:
      - name: Install Flatpak packages
        flatpak:
          name:
            - rest.insomnia.Insomnia
            - org.pitivi.Pitivi
            - org.remmina.Remmina
            - org.gimp.GIMP
            - org.inkscape.Inkscape
            - com.discordapp.Discord
            - org.mozilla.firefox
            - com.valvesoftware.Steam
            - io.dbeaver.DBeaverCommunity
            - net.cozic.joplin_desktop
          method: system
          state: present
        
      - name: Vscode and extentions
        shell: |
              sudo rpmkeys --import https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
              printf "[gitlab.com_paulcarroty_vscodium_repo]\nname=download.vscodium.com\nbaseurl=https://download.vscodium.com/rpms/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg\nmetadata_expire=1h" | sudo tee -a /etc/yum.repos.d/vscodium.repo
              sudo dnf install codium -y
