  - name: Desktop
    hosts: localhost
    tasks:

      - name: add vscodium repo with rpmkeys
        become: true
        shell: |
              rpmkeys --import https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
              printf "[gitlab.com_paulcarroty_vscodium_repo]\nname=download.vscodium.com\nbaseurl=https://download.vscodium.com/rpms/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg\nmetadata_expire=1h" | sudo tee -a /etc/yum.repos.d/vscodium.repo
      
      
      - name: Install Flatpak and vscode if necessary
        become: true
        package:
          name: 
            - flatpak
            - codium
            - i3
            - i3status
            - compton
            - tint2
            - dunst
            - xfce4-panele4-
          state: present



      - name: Install Flatpak Apps
        become: true
        flatpak:
          name:
            - rest.insomnia.Insomnia
            - org.pitivi.Pitivi
            - org.remmina.Remmina
            - org.gimp.GIMP
            - org.inkscape.Inkscape
            - com.discordapp.Discord
            - org.mozilla.firefox
            - com.valvesoftware.Steam
            - io.dbeaver.DBeaverCommunity
            - net.cozic.joplin_desktop
          method: system
          state: present

      - name: Install vscodium extensions
        command: codium --install-extension "{{ item }}"
        with_items:
          - jdinhlife.gruvbox
          - ms-python.python
          - ms-toolsai.jupyter
          - ms-toolsai.jupyter-keymap
          - ms-toolsai.jupyter-renderers
          - ms-toolsai.vscode-jupyter-cell-tags
          - ms-toolsai.vscode-jupyter-slideshow
          - PKief.material-icon-theme
          - rust-lang.rust
          - rust-lang.rust-analyzer
          - s-nlf-fh.glassit
          - sainnhe.gruvbox-material
          - svelte.svelte-vscode
          - tamasfe.even-better-toml
          - vscodevim.vim
          - yandeu.five-server

  