- name: Configure Ubuntu/Debian/Fedora/RHEL machine
  hosts: localhost
  vars:
    config_path: "$HOME/repos/myconfig"

  tasks:
    - name: Enable COPRs (Fedora/RHEL)
      become: true
      command: 'dnf copr enable {{ item }} -y'
      with_items:
      # - zeno/scrcpy
        - atim/starship
        - atim/nushell
        - varlad/helix

    - name: Install minimal packages
      become: true
      package:
        name:
          - ranger
          - stow
          - fzf
          - tmux
          - htop
          - docker
          - docker-compose
          - python3-pip
          - neovim
          - git
          - bat
          - fontawesome5*
          - fira-code-fonts
          - helix
        state: present
        update_cache: false
        install_weak_deps: false
      tags: 
        - minimal
        - cli

    - name: Install packages
      become: true
      package:
        name:
          - wget
          - curl
          - nodejs
          - npm
          - ansible
          - jq
          - unzip
          - zip
          - hyperfine
          - tokei
          - just
          - nushell
          - python3-pip
          - docker-compose
          - python3-beautifulsoup4
          - python3-numpy
          - python3-pandas
          - python3-matplotlib
          - python3-requests
          - python3-fastapi
          - python3-scrapy
        state: present
        update_cache: false
        install_weak_deps: false
      tags: 
        - cli


    - name: Clone config
      git:
        repo: https://github.com/mehdi-yc/postinstall
        dest: "{{ config_path }}"
        force: true
        update: true
      tags: 
        - minimal
        - cli



    - name: Backup .bashrc and .Xresources
      command: mv "{{ item }}" "{{ item }}.bak"
      args:
        creates: "{{ item }}.bak"
      with_items:
        - ~/.bashrc
        - ~/.Xresources
      ignore_errors: yes
      tags: 
        - minimal
        - cli

          
    - name: Stow the config files
      command: stow -vRd "{{ config_path }}/" -t $HOME config
      tags: 
          - minimal
          - cli

    - name: Ensure Fonts directory exists
      become: true
      file:
        path: /usr/share/fonts/truetype/
        recurse: true
        state: directory
      tags: 
        - cli

    - name: Download FiraCode Regular Nerd Font
      become: true
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/raw/v3.0.2/patched-fonts/FiraCode/Regular/FiraCodeNerdFont-Regular.ttf
        dest: /usr/share/fonts/truetype/FiraCode-Regular.ttf
        tags: 
          - cli

    - name: add vscodium repo with rpmkeys
      become: true
      shell: |
            rpmkeys --import https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
            printf "[gitlab.com_paulcarroty_vscodium_repo]\nname=download.vscodium.com\nbaseurl=https://download.vscodium.com/rpms/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg\nmetadata_expire=1h" | sudo tee -a /etc/yum.repos.d/vscodium.repo
      tags: desktop,fedora

    - name: Install Flatpak and Codium (VSCodium)
      become: true
      package:
        name:
          - flatpak
          - codium
        state: present


    - name: Install i3 and related packages
      become: true
      package:
        name:
          - i3
          - i3status
          - picom
          - dunst
          - feh
        state: present
      tags: minimal


    - name: Install Flatpak Apps
      become: true
      flatpak:
        name:
          - rest.insomnia.Insomnia
          - org.pitivi.Pitivi
          - org.remmina.Remmina
          - org.gimp.GIMP
          - org.inkscape.Inkscape
          - com.discordapp.Discord
          - org.mozilla.firefox
          - com.valvesoftware.Steam
          - io.dbeaver.DBeaverCommunity
          - net.cozic.joplin_desktop
          - org.flameshot.Flameshot
        method: system
        state: present


    - name: Install VSCodium extensions
      command: codium --install-extension "{{ item }}"
      with_items:
        - asvetliakov.vscode-neovim
        - bradlc.vscode-tailwindcss
        - innoverio.vscode-dbt-power-user
        - jdinhlife.gruvbox
        - ms-python.python
        - ms-toolsai.jupyter
        - ms-toolsai.jupyter-keymap
        - ms-toolsai.jupyter-renderers
        - ms-toolsai.vscode-jupyter-cell-tags
        - ms-toolsai.vscode-jupyter-slideshow
        - mtxr.sqltools
        - mtxr.sqltools-driver-pg
        - mtxr.sqltools-driver-sqlite
        - PKief.material-icon-theme
        - rust-lang.rust
        - rust-lang.rust-analyzer
        - s-nlf-fh.glassit
        - sainnhe.gruvbox-material
        - samuelcolvin.jinjahtml
        - svelte.svelte-vscode
        - tamasfe.even-better-toml
        - ultram4rine.sqltools-clickhouse-driver
        - vscodevim.vim
        - yandeu.five-server

