- name: i3_ubuntu
  hosts: localhost
  vars:
    config_path: "$HOME/repos/myconfig"


  tasks:

    - name: install i3 + config
      become: true
      package:
        name: 
          - i3
          - i3status
          - picom
          - dunst
          - network-manager
        state: present



    - name: Install required snaps
      become: true
      snap:
        name: "{{ snaps }}"
        state: present
      vars:
        snaps:
          - insomnia
          #- pitivi
          - remmina
          #- gimp
          - inkscape
          - discord
          - firefox
          #- dbeaver-ce
          - joplin
          - flameshot
          - codium
          - starship


    - name: Install vscodium extensions
      command: codium --install-extension "{{ item }}"
      with_items:
        - asvetliakov.vscode-neovim
        - bradlc.vscode-tailwindcss
        - jdinhlife.gruvbox
        - ms-python.python
        - PKief.material-icon-theme
        - rust-lang.rust-analyzer
        - s-nlf-fh.glassit
        - sainnhe.gruvbox-material
        - samuelcolvin.jinjahtml
        - svelte.svelte-vscode
        - tamasfe.even-better-toml
        - yandeu.five-server



    - name: Install required packages from APT
      become: true
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - ranger
          - stow
          - fzf
          - tmux
          - htop
          - python3-pip
          - git
          - bat
          - cargo
          - rustc
          - docker 
          - docker-compose
          - python3-beautifulsoup4
          - python3-numpy
          - python3-pandas
          - python3-matplotlib
          - python3-requests
          - python3-fastapi
          - python3-scrapy
          - fish

    - name: Clone config
      git:
        repo: https://github.com/mehdi-yc/postinstall
        dest: "{{config_path}}"
        update: true



    - name: Backup .bashrc and .Xresources
      command: mv "{{ item }}" "{{ item }}.bak"
      args:
        creates: "{{ item }}.bak"
      with_items:
        - ~/.bashrc
        - ~/.Xresources



    - name: Stow the config files
      command: stow -vRd "{{config_path}}/distrobox_builder/" -t $HOME config
      tags: minimal
    
    - name: chmod the i3 scripts
      command: chmod +x ~/.config/i3/*


    - name: Download FiraCode Regular Nerd Font
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/raw/v3.0.2/patched-fonts/FiraCode/Regular/FiraCodeNerdFont-Regular.ttf
        dest: /usr/share/fonts/truetype/FiraCode-Regular.ttf




