[username]
style_user = "yellow bold"
style_root = "red bold"
format = "([$user]($style)) "
show_always = true

[hostname]
ssh_only = false

[character]   # The name of the module we are configuring is "character"
success_symbol = " [➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = " [✗](bold red)"

[directory]
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "bold  blue"

[cmd_duration]
min_time = 4
show_milliseconds = false
style = "bold green "
format = "- [$duration]($style)"